### ISSUE TITLE
pip安装的0.7.2启动失败

### ISSUE THREAD

**Issue by weisong82** [KenyonY/openai-forward#130]
### Initial Checks

- [X] My `openai-forward` version is not lower than v0.7.0

### Issue Description

(base) C:\Users\Administrator>aifd run
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\anaconda3\Scripts\aifd.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\anaconda3\lib\site-packages\openai_forward\__main__.py", line 232, in main
    fire.Fire(Cli)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Administrator\anaconda3\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\openai_forward\__main__.py", line 55, in run
    uvicorn.run(
  File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\Administrator\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\anaconda3\lib\site-packages\openai_forward\app.py", line 7, in <module>
    from .forward import ForwardManager
  File "C:\Users\Administrator\anaconda3\lib\site-packages\openai_forward\forward\__init__.py", line 3, in <module>
    from ..settings import (
  File "C:\Users\Administrator\anaconda3\lib\site-packages\openai_forward\settings.py", line 117, in <module>
    OPENAI_API_KEY = env2dict("OPENAI_API_KEY")
  File "C:\Users\Administrator\anaconda3\lib\site-packages\openai_forward\helper.py", line 171, in env2dict
    return json.loads(env_str)
  File "C:\Users\Administrator\anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Environment

(base) C:\Users\Administrator>python -c "import sys,platform; print('python: {}\nOS: {}'.format(sys.version, platform.system()));"
python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
OS: Windows

(base) C:\Users\Administrator>python -c "import openai_forward; print('openai_forward: {}'.format(openai_forward.__version__));"
openai_forward: 0.7.2

### Final Step

- [X] I believe my description above is detailed enough for developers to reproduce the issue.

**Comment by KenyonY** [comment]
看上去是读取.env文件中变量时出了问题，Windows下可能需要将变量值写到一行

**Comment by weisong82** [comment]
> 看上去是读取.env文件中变量时出了问题，可参照本仓库下.env文件进行设置

我试过在没有.env文件的路径下启动也是这个错。

**Comment by KenyonY** [comment]
因为你的环境变量中已经被设置过其它项目的OPENAI_API_KEY 值。 可尝试下面两种方式启动 
1. 修改.env文件中的OPENAI_API_KEY 为正确格式
2. 启动命令修改为 `OPENAI_API_KEY='' aifd run`
